// flow-typed signature: fb7bb04e8cd2325ab27b09a1a0197214
// flow-typed version: <<STUB>>/cfonts_v^1.1.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cfonts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cfonts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cfonts/bin/font' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cfonts/bin/font.js' {
  declare module.exports: $Exports<'cfonts/bin/font'>;
}
declare module 'cfonts/index' {
  declare module.exports: $Exports<'cfonts'>;
}
declare module 'cfonts/index.js' {
  declare module.exports: $Exports<'cfonts'>;
}
