// flow-typed signature: d96bd2a1a7a77fbbe5fb0d2d299534f4
// flow-typed version: <<STUB>>/dbly-linked-list_v^0.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dbly-linked-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dbly-linked-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dbly-linked-list/lib/iterator' {
  declare module.exports: any;
}

declare module 'dbly-linked-list/lib/list-node' {
  declare module.exports: any;
}

declare module 'dbly-linked-list/test/list.spec' {
  declare module.exports: any;
}

declare module 'dbly-linked-list/test/node.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dbly-linked-list/index' {
  declare module.exports: $Exports<'dbly-linked-list'>;
}
declare module 'dbly-linked-list/index.js' {
  declare module.exports: $Exports<'dbly-linked-list'>;
}
declare module 'dbly-linked-list/lib/iterator.js' {
  declare module.exports: $Exports<'dbly-linked-list/lib/iterator'>;
}
declare module 'dbly-linked-list/lib/list-node.js' {
  declare module.exports: $Exports<'dbly-linked-list/lib/list-node'>;
}
declare module 'dbly-linked-list/test/list.spec.js' {
  declare module.exports: $Exports<'dbly-linked-list/test/list.spec'>;
}
declare module 'dbly-linked-list/test/node.spec.js' {
  declare module.exports: $Exports<'dbly-linked-list/test/node.spec'>;
}
