// flow-typed signature: 2f086ac2de1b0ddc9b67088de9dbd0ba
// flow-typed version: <<STUB>>/eslint-plugin-vue_v^4.5.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-vue/lib/configs/base' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/essential' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/configs/strongly-recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/processor' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/attribute-hyphenation' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/attributes-order' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/comment-directive' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-newline' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-end-tags' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-quotes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/html-self-closing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/jsx-uses-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/max-attributes-per-line' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/name-property-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-async-in-computed-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-confusing-v-for-v-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-dupe-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attributes' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-multi-spaces' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-parsing-error' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-reserved-keys' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-shared-component-data' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-template-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-textarea-mustache' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/no-unused-vars' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/order-in-components' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/prop-name-casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-component-is' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-default-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-prop-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-render-return' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-v-for-key' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/require-valid-default-prop' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/return-in-computed-property' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/script-indent' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/this-in-template' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-bind-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/v-on-style' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-template-root' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-bind' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-cloak' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-else-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-else' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-for' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-html' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-if' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-model' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-on' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-once' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-pre' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-show' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/rules/valid-v-text' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/casing' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/indent-common' {
  declare module.exports: any;
}

declare module 'eslint-plugin-vue/lib/utils/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-vue/lib/configs/base.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/base'>;
}
declare module 'eslint-plugin-vue/lib/configs/essential.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/essential'>;
}
declare module 'eslint-plugin-vue/lib/configs/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/recommended'>;
}
declare module 'eslint-plugin-vue/lib/configs/strongly-recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/configs/strongly-recommended'>;
}
declare module 'eslint-plugin-vue/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/index'>;
}
declare module 'eslint-plugin-vue/lib/processor.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/processor'>;
}
declare module 'eslint-plugin-vue/lib/rules/attribute-hyphenation.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/attribute-hyphenation'>;
}
declare module 'eslint-plugin-vue/lib/rules/attributes-order.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/attributes-order'>;
}
declare module 'eslint-plugin-vue/lib/rules/comment-directive.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/comment-directive'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-newline.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-closing-bracket-newline'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-closing-bracket-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-end-tags.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-end-tags'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-indent'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-quotes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-quotes'>;
}
declare module 'eslint-plugin-vue/lib/rules/html-self-closing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/html-self-closing'>;
}
declare module 'eslint-plugin-vue/lib/rules/jsx-uses-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/jsx-uses-vars'>;
}
declare module 'eslint-plugin-vue/lib/rules/max-attributes-per-line.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/max-attributes-per-line'>;
}
declare module 'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/mustache-interpolation-spacing'>;
}
declare module 'eslint-plugin-vue/lib/rules/name-property-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/name-property-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-async-in-computed-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-async-in-computed-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-confusing-v-for-v-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-confusing-v-for-v-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-dupe-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-dupe-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-duplicate-attributes.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-duplicate-attributes'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-multi-spaces.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-multi-spaces'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-parsing-error.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-parsing-error'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-reserved-keys.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-reserved-keys'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-shared-component-data.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-shared-component-data'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-side-effects-in-computed-properties'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-template-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-template-key'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-textarea-mustache.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-textarea-mustache'>;
}
declare module 'eslint-plugin-vue/lib/rules/no-unused-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/no-unused-vars'>;
}
declare module 'eslint-plugin-vue/lib/rules/order-in-components.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/order-in-components'>;
}
declare module 'eslint-plugin-vue/lib/rules/prop-name-casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/prop-name-casing'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-component-is.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-component-is'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-default-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-default-prop'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-prop-types.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-prop-types'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-render-return.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-render-return'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-v-for-key.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-v-for-key'>;
}
declare module 'eslint-plugin-vue/lib/rules/require-valid-default-prop.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/require-valid-default-prop'>;
}
declare module 'eslint-plugin-vue/lib/rules/return-in-computed-property.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/return-in-computed-property'>;
}
declare module 'eslint-plugin-vue/lib/rules/script-indent.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/script-indent'>;
}
declare module 'eslint-plugin-vue/lib/rules/this-in-template.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/this-in-template'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-bind-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-bind-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/v-on-style.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/v-on-style'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-template-root.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-template-root'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-bind.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-bind'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-cloak.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-cloak'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-else-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-else-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-else.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-else'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-for.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-for'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-html.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-html'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-if.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-if'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-model.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-model'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-on.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-on'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-once.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-once'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-pre.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-pre'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-show.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-show'>;
}
declare module 'eslint-plugin-vue/lib/rules/valid-v-text.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/rules/valid-v-text'>;
}
declare module 'eslint-plugin-vue/lib/utils/casing.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/casing'>;
}
declare module 'eslint-plugin-vue/lib/utils/indent-common.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/indent-common'>;
}
declare module 'eslint-plugin-vue/lib/utils/index.js' {
  declare module.exports: $Exports<'eslint-plugin-vue/lib/utils/index'>;
}
