// flow-typed signature: 6303616b499b8da5c28e30f560efb1ff
// flow-typed version: <<STUB>>/file-size_v^1.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-size'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-size' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'file-size/test/conversions' {
  declare module.exports: any;
}

declare module 'file-size/test/exports' {
  declare module.exports: any;
}

declare module 'file-size/test/human' {
  declare module.exports: any;
}

// Filename aliases
declare module 'file-size/index' {
  declare module.exports: $Exports<'file-size'>;
}
declare module 'file-size/index.js' {
  declare module.exports: $Exports<'file-size'>;
}
declare module 'file-size/test/conversions.js' {
  declare module.exports: $Exports<'file-size/test/conversions'>;
}
declare module 'file-size/test/exports.js' {
  declare module.exports: $Exports<'file-size/test/exports'>;
}
declare module 'file-size/test/human.js' {
  declare module.exports: $Exports<'file-size/test/human'>;
}
