// flow-typed signature: ea0d8af009eab42d8c18b027f41ab04b
// flow-typed version: <<STUB>>/jpex_v^2.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jpex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jpex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jpex/dist/jpex' {
  declare module.exports: any;
}

declare module 'jpex/dist/jpex.min' {
  declare module.exports: any;
}

declare module 'jpex/src/class/index' {
  declare module.exports: any;
}

declare module 'jpex/src/class/privates' {
  declare module.exports: any;
}

declare module 'jpex/src/class/resolve' {
  declare module.exports: any;
}

declare module 'jpex/src/constants' {
  declare module.exports: any;
}

declare module 'jpex/src/factories/constant' {
  declare module.exports: any;
}

declare module 'jpex/src/factories/decorator' {
  declare module.exports: any;
}

declare module 'jpex/src/factories/factory' {
  declare module.exports: any;
}

declare module 'jpex/src/factories/index' {
  declare module.exports: any;
}

declare module 'jpex/src/factories/jaas' {
  declare module.exports: any;
}

declare module 'jpex/src/factories/service' {
  declare module.exports: any;
}

declare module 'jpex/src/factories/wrapper' {
  declare module.exports: any;
}

declare module 'jpex/src/hasOwn' {
  declare module.exports: any;
}

declare module 'jpex/src/index' {
  declare module.exports: any;
}

declare module 'jpex/src/instantiator' {
  declare module.exports: any;
}

declare module 'jpex/src/isNode' {
  declare module.exports: any;
}

declare module 'jpex/src/jpexError' {
  declare module.exports: any;
}

declare module 'jpex/src/plugins/index' {
  declare module.exports: any;
}

declare module 'jpex/src/resolver/factories' {
  declare module.exports: any;
}

declare module 'jpex/src/resolver/index' {
  declare module.exports: any;
}

declare module 'jpex/src/unsafeRequire' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jpex/dist/jpex.js' {
  declare module.exports: $Exports<'jpex/dist/jpex'>;
}
declare module 'jpex/dist/jpex.min.js' {
  declare module.exports: $Exports<'jpex/dist/jpex.min'>;
}
declare module 'jpex/src/class/index.js' {
  declare module.exports: $Exports<'jpex/src/class/index'>;
}
declare module 'jpex/src/class/privates.js' {
  declare module.exports: $Exports<'jpex/src/class/privates'>;
}
declare module 'jpex/src/class/resolve.js' {
  declare module.exports: $Exports<'jpex/src/class/resolve'>;
}
declare module 'jpex/src/constants.js' {
  declare module.exports: $Exports<'jpex/src/constants'>;
}
declare module 'jpex/src/factories/constant.js' {
  declare module.exports: $Exports<'jpex/src/factories/constant'>;
}
declare module 'jpex/src/factories/decorator.js' {
  declare module.exports: $Exports<'jpex/src/factories/decorator'>;
}
declare module 'jpex/src/factories/factory.js' {
  declare module.exports: $Exports<'jpex/src/factories/factory'>;
}
declare module 'jpex/src/factories/index.js' {
  declare module.exports: $Exports<'jpex/src/factories/index'>;
}
declare module 'jpex/src/factories/jaas.js' {
  declare module.exports: $Exports<'jpex/src/factories/jaas'>;
}
declare module 'jpex/src/factories/service.js' {
  declare module.exports: $Exports<'jpex/src/factories/service'>;
}
declare module 'jpex/src/factories/wrapper.js' {
  declare module.exports: $Exports<'jpex/src/factories/wrapper'>;
}
declare module 'jpex/src/hasOwn.js' {
  declare module.exports: $Exports<'jpex/src/hasOwn'>;
}
declare module 'jpex/src/index.js' {
  declare module.exports: $Exports<'jpex/src/index'>;
}
declare module 'jpex/src/instantiator.js' {
  declare module.exports: $Exports<'jpex/src/instantiator'>;
}
declare module 'jpex/src/isNode.js' {
  declare module.exports: $Exports<'jpex/src/isNode'>;
}
declare module 'jpex/src/jpexError.js' {
  declare module.exports: $Exports<'jpex/src/jpexError'>;
}
declare module 'jpex/src/plugins/index.js' {
  declare module.exports: $Exports<'jpex/src/plugins/index'>;
}
declare module 'jpex/src/resolver/factories.js' {
  declare module.exports: $Exports<'jpex/src/resolver/factories'>;
}
declare module 'jpex/src/resolver/index.js' {
  declare module.exports: $Exports<'jpex/src/resolver/index'>;
}
declare module 'jpex/src/unsafeRequire.js' {
  declare module.exports: $Exports<'jpex/src/unsafeRequire'>;
}
