// flow-typed signature: a238d15b35a7b233e651a3f0f2dd1af7
// flow-typed version: <<STUB>>/karma-electron_v^5.1.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'karma-electron'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'karma-electron' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'karma-electron/bin/verify-failure' {
  declare module.exports: any;
}

declare module 'karma-electron/lib/electron-launcher' {
  declare module.exports: any;
}

declare module 'karma-electron/lib/index' {
  declare module.exports: any;
}

declare module 'karma-electron/lib/karma-electron-launcher' {
  declare module.exports: any;
}

declare module 'karma-electron/lib/karma-electron-preprocessor' {
  declare module.exports: any;
}

declare module 'karma-electron/lib/node-integration-iframe.mustache' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/custom-context-file-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/eof-comment-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/failure-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/filename-override-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/karma-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/karma.conf' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/main-require-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/node-common-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/node-require-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/node-script-src-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/phantomjs-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/source-map-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/success-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/test-files/main-require' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/test-files/submodule' {
  declare module.exports: any;
}

declare module 'karma-electron/test/integration-test/uncaught-exception-test' {
  declare module.exports: any;
}

declare module 'karma-electron/test/reference/index' {
  declare module.exports: any;
}

declare module 'karma-electron/test/reference/js/require-main' {
  declare module.exports: any;
}

declare module 'karma-electron/test/reference/js/require-submodule' {
  declare module.exports: any;
}

declare module 'karma-electron/test/reference/js/script-src-main' {
  declare module.exports: any;
}

declare module 'karma-electron/test/reference/js/script-src-submodule' {
  declare module.exports: any;
}

// Filename aliases
declare module 'karma-electron/bin/verify-failure.js' {
  declare module.exports: $Exports<'karma-electron/bin/verify-failure'>;
}
declare module 'karma-electron/lib/electron-launcher.js' {
  declare module.exports: $Exports<'karma-electron/lib/electron-launcher'>;
}
declare module 'karma-electron/lib/index.js' {
  declare module.exports: $Exports<'karma-electron/lib/index'>;
}
declare module 'karma-electron/lib/karma-electron-launcher.js' {
  declare module.exports: $Exports<'karma-electron/lib/karma-electron-launcher'>;
}
declare module 'karma-electron/lib/karma-electron-preprocessor.js' {
  declare module.exports: $Exports<'karma-electron/lib/karma-electron-preprocessor'>;
}
declare module 'karma-electron/lib/node-integration-iframe.mustache.js' {
  declare module.exports: $Exports<'karma-electron/lib/node-integration-iframe.mustache'>;
}
declare module 'karma-electron/test/integration-test/custom-context-file-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/custom-context-file-test'>;
}
declare module 'karma-electron/test/integration-test/eof-comment-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/eof-comment-test'>;
}
declare module 'karma-electron/test/integration-test/failure-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/failure-test'>;
}
declare module 'karma-electron/test/integration-test/filename-override-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/filename-override-test'>;
}
declare module 'karma-electron/test/integration-test/karma-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/karma-test'>;
}
declare module 'karma-electron/test/integration-test/karma.conf.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/karma.conf'>;
}
declare module 'karma-electron/test/integration-test/main-require-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/main-require-test'>;
}
declare module 'karma-electron/test/integration-test/node-common-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/node-common-test'>;
}
declare module 'karma-electron/test/integration-test/node-require-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/node-require-test'>;
}
declare module 'karma-electron/test/integration-test/node-script-src-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/node-script-src-test'>;
}
declare module 'karma-electron/test/integration-test/phantomjs-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/phantomjs-test'>;
}
declare module 'karma-electron/test/integration-test/source-map-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/source-map-test'>;
}
declare module 'karma-electron/test/integration-test/success-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/success-test'>;
}
declare module 'karma-electron/test/integration-test/test-files/main-require.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/test-files/main-require'>;
}
declare module 'karma-electron/test/integration-test/test-files/submodule.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/test-files/submodule'>;
}
declare module 'karma-electron/test/integration-test/uncaught-exception-test.js' {
  declare module.exports: $Exports<'karma-electron/test/integration-test/uncaught-exception-test'>;
}
declare module 'karma-electron/test/reference/index.js' {
  declare module.exports: $Exports<'karma-electron/test/reference/index'>;
}
declare module 'karma-electron/test/reference/js/require-main.js' {
  declare module.exports: $Exports<'karma-electron/test/reference/js/require-main'>;
}
declare module 'karma-electron/test/reference/js/require-submodule.js' {
  declare module.exports: $Exports<'karma-electron/test/reference/js/require-submodule'>;
}
declare module 'karma-electron/test/reference/js/script-src-main.js' {
  declare module.exports: $Exports<'karma-electron/test/reference/js/script-src-main'>;
}
declare module 'karma-electron/test/reference/js/script-src-submodule.js' {
  declare module.exports: $Exports<'karma-electron/test/reference/js/script-src-submodule'>;
}
