// flow-typed signature: 249c2994e63ada4608976b48cdae6f01
// flow-typed version: <<STUB>>/lolex_v^2.3.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lolex'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lolex' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lolex/lolex' {
  declare module.exports: any;
}

declare module 'lolex/src/lolex-src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lolex/lolex.js' {
  declare module.exports: $Exports<'lolex/lolex'>;
}
declare module 'lolex/src/lolex-src.js' {
  declare module.exports: $Exports<'lolex/src/lolex-src'>;
}
