// flow-typed signature: 8476bee21085b59b77f5ef6f934c40a1
// flow-typed version: <<STUB>>/multispinner_v^0.2.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multispinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'multispinner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multispinner/extras/examples/cli-with-promises/index' {
  declare module.exports: any;
}

declare module 'multispinner/extras/examples/customAnimation' {
  declare module.exports: any;
}

declare module 'multispinner/extras/examples/events' {
  declare module.exports: any;
}

declare module 'multispinner/extras/examples/randomInfiniteLoop' {
  declare module.exports: any;
}

declare module 'multispinner/lib/constants' {
  declare module.exports: any;
}

declare module 'multispinner/lib/errs' {
  declare module.exports: any;
}

declare module 'multispinner/lib/spinners' {
  declare module.exports: any;
}

declare module 'multispinner/lib/validOpts' {
  declare module.exports: any;
}

declare module 'multispinner/test/errs' {
  declare module.exports: any;
}

declare module 'multispinner/test/methods' {
  declare module.exports: any;
}

declare module 'multispinner/test/spinners' {
  declare module.exports: any;
}

declare module 'multispinner/test/utils/genSpinners' {
  declare module.exports: any;
}

declare module 'multispinner/test/validOpts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multispinner/extras/examples/cli-with-promises/index.js' {
  declare module.exports: $Exports<'multispinner/extras/examples/cli-with-promises/index'>;
}
declare module 'multispinner/extras/examples/customAnimation.js' {
  declare module.exports: $Exports<'multispinner/extras/examples/customAnimation'>;
}
declare module 'multispinner/extras/examples/events.js' {
  declare module.exports: $Exports<'multispinner/extras/examples/events'>;
}
declare module 'multispinner/extras/examples/randomInfiniteLoop.js' {
  declare module.exports: $Exports<'multispinner/extras/examples/randomInfiniteLoop'>;
}
declare module 'multispinner/index' {
  declare module.exports: $Exports<'multispinner'>;
}
declare module 'multispinner/index.js' {
  declare module.exports: $Exports<'multispinner'>;
}
declare module 'multispinner/lib/constants.js' {
  declare module.exports: $Exports<'multispinner/lib/constants'>;
}
declare module 'multispinner/lib/errs.js' {
  declare module.exports: $Exports<'multispinner/lib/errs'>;
}
declare module 'multispinner/lib/spinners.js' {
  declare module.exports: $Exports<'multispinner/lib/spinners'>;
}
declare module 'multispinner/lib/validOpts.js' {
  declare module.exports: $Exports<'multispinner/lib/validOpts'>;
}
declare module 'multispinner/test/errs.js' {
  declare module.exports: $Exports<'multispinner/test/errs'>;
}
declare module 'multispinner/test/methods.js' {
  declare module.exports: $Exports<'multispinner/test/methods'>;
}
declare module 'multispinner/test/spinners.js' {
  declare module.exports: $Exports<'multispinner/test/spinners'>;
}
declare module 'multispinner/test/utils/genSpinners.js' {
  declare module.exports: $Exports<'multispinner/test/utils/genSpinners'>;
}
declare module 'multispinner/test/validOpts.js' {
  declare module.exports: $Exports<'multispinner/test/validOpts'>;
}
