// flow-typed signature: 2e0d2603d49f96ad898bbc7a2d4d8269
// flow-typed version: <<STUB>>/tail_v^1.2.3/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tail'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tail' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tail/lib/tail' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tail/lib/tail.js' {
  declare module.exports: $Exports<'tail/lib/tail'>;
}
