// flow-typed signature: 9d610ecdabd08e96a36e1c8037e5ef79
// flow-typed version: <<STUB>>/vue-loader_v^14.2.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-loader/lib/helpers' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/loader' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/parser' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/runtime/component-normalizer' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/selector' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/index' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/load-postcss-config' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/plugins/scope-id' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/style-compiler/plugins/trim' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/index' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/modules/transform-require' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/modules/transform-srcset' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/preprocessor' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/template-compiler/url-to-require' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/utils/normalize' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/utils/options-cache' {
  declare module.exports: any;
}

declare module 'vue-loader/lib/utils/try-require' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-loader/index' {
  declare module.exports: $Exports<'vue-loader'>;
}
declare module 'vue-loader/index.js' {
  declare module.exports: $Exports<'vue-loader'>;
}
declare module 'vue-loader/lib/helpers.js' {
  declare module.exports: $Exports<'vue-loader/lib/helpers'>;
}
declare module 'vue-loader/lib/loader.js' {
  declare module.exports: $Exports<'vue-loader/lib/loader'>;
}
declare module 'vue-loader/lib/parser.js' {
  declare module.exports: $Exports<'vue-loader/lib/parser'>;
}
declare module 'vue-loader/lib/runtime/component-normalizer.js' {
  declare module.exports: $Exports<'vue-loader/lib/runtime/component-normalizer'>;
}
declare module 'vue-loader/lib/selector.js' {
  declare module.exports: $Exports<'vue-loader/lib/selector'>;
}
declare module 'vue-loader/lib/style-compiler/index.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/index'>;
}
declare module 'vue-loader/lib/style-compiler/load-postcss-config.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/load-postcss-config'>;
}
declare module 'vue-loader/lib/style-compiler/plugins/scope-id.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/plugins/scope-id'>;
}
declare module 'vue-loader/lib/style-compiler/plugins/trim.js' {
  declare module.exports: $Exports<'vue-loader/lib/style-compiler/plugins/trim'>;
}
declare module 'vue-loader/lib/template-compiler/index.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/index'>;
}
declare module 'vue-loader/lib/template-compiler/modules/transform-require.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/modules/transform-require'>;
}
declare module 'vue-loader/lib/template-compiler/modules/transform-srcset.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/modules/transform-srcset'>;
}
declare module 'vue-loader/lib/template-compiler/preprocessor.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/preprocessor'>;
}
declare module 'vue-loader/lib/template-compiler/url-to-require.js' {
  declare module.exports: $Exports<'vue-loader/lib/template-compiler/url-to-require'>;
}
declare module 'vue-loader/lib/utils/normalize.js' {
  declare module.exports: $Exports<'vue-loader/lib/utils/normalize'>;
}
declare module 'vue-loader/lib/utils/options-cache.js' {
  declare module.exports: $Exports<'vue-loader/lib/utils/options-cache'>;
}
declare module 'vue-loader/lib/utils/try-require.js' {
  declare module.exports: $Exports<'vue-loader/lib/utils/try-require'>;
}
