// flow-typed signature: 7bad372e4a96404a166a1b2722953e27
// flow-typed version: <<STUB>>/vue-inject_v^2.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-inject'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-inject' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-inject/dist/vue-inject' {
  declare module.exports: any;
}

declare module 'vue-inject/dist/vue-inject.min' {
  declare module.exports: any;
}

declare module 'vue-inject/src/base' {
  declare module.exports: any;
}

declare module 'vue-inject/src/index' {
  declare module.exports: any;
}

declare module 'vue-inject/src/install' {
  declare module.exports: any;
}

declare module 'vue-inject/src/plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-inject/dist/vue-inject.js' {
  declare module.exports: $Exports<'vue-inject/dist/vue-inject'>;
}
declare module 'vue-inject/dist/vue-inject.min.js' {
  declare module.exports: $Exports<'vue-inject/dist/vue-inject.min'>;
}
declare module 'vue-inject/src/base.js' {
  declare module.exports: $Exports<'vue-inject/src/base'>;
}
declare module 'vue-inject/src/index.js' {
  declare module.exports: $Exports<'vue-inject/src/index'>;
}
declare module 'vue-inject/src/install.js' {
  declare module.exports: $Exports<'vue-inject/src/install'>;
}
declare module 'vue-inject/src/plugin.js' {
  declare module.exports: $Exports<'vue-inject/src/plugin'>;
}
