// flow-typed signature: 8b2c6b6f7129fdfa599cf7fb3591b83b
// flow-typed version: <<STUB>>/vue-svg-loader_v^0.5.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-svg-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-svg-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'vue-svg-loader/index' {
  declare module.exports: $Exports<'vue-svg-loader'>;
}
declare module 'vue-svg-loader/index.js' {
  declare module.exports: $Exports<'vue-svg-loader'>;
}
