// flow-typed signature: 5f53fc6bae259fb4875e68bb81f0492c
// flow-typed version: <<STUB>>/winston-transport_v^4.2.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'winston-transport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'winston-transport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'winston-transport/legacy' {
  declare module.exports: any;
}

declare module 'winston-transport/test/fixtures/index' {
  declare module.exports: any;
}

declare module 'winston-transport/test/fixtures/legacy-transport' {
  declare module.exports: any;
}

declare module 'winston-transport/test/fixtures/parent' {
  declare module.exports: any;
}

declare module 'winston-transport/test/fixtures/simple-class-transport' {
  declare module.exports: any;
}

declare module 'winston-transport/test/fixtures/simple-proto-transport' {
  declare module.exports: any;
}

declare module 'winston-transport/test/index.test' {
  declare module.exports: any;
}

declare module 'winston-transport/test/inheritance.test' {
  declare module.exports: any;
}

declare module 'winston-transport/test/legacy.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'winston-transport/index' {
  declare module.exports: $Exports<'winston-transport'>;
}
declare module 'winston-transport/index.js' {
  declare module.exports: $Exports<'winston-transport'>;
}
declare module 'winston-transport/legacy.js' {
  declare module.exports: $Exports<'winston-transport/legacy'>;
}
declare module 'winston-transport/test/fixtures/index.js' {
  declare module.exports: $Exports<'winston-transport/test/fixtures/index'>;
}
declare module 'winston-transport/test/fixtures/legacy-transport.js' {
  declare module.exports: $Exports<'winston-transport/test/fixtures/legacy-transport'>;
}
declare module 'winston-transport/test/fixtures/parent.js' {
  declare module.exports: $Exports<'winston-transport/test/fixtures/parent'>;
}
declare module 'winston-transport/test/fixtures/simple-class-transport.js' {
  declare module.exports: $Exports<'winston-transport/test/fixtures/simple-class-transport'>;
}
declare module 'winston-transport/test/fixtures/simple-proto-transport.js' {
  declare module.exports: $Exports<'winston-transport/test/fixtures/simple-proto-transport'>;
}
declare module 'winston-transport/test/index.test.js' {
  declare module.exports: $Exports<'winston-transport/test/index.test'>;
}
declare module 'winston-transport/test/inheritance.test.js' {
  declare module.exports: $Exports<'winston-transport/test/inheritance.test'>;
}
declare module 'winston-transport/test/legacy.test.js' {
  declare module.exports: $Exports<'winston-transport/test/legacy.test'>;
}
