export default {
  // MUTATIONS
  REQUEST_FAIL: 'REQUEST_FAIL',

  INIT_SUCCESS: 'INIT_SUCCESS',
  INIT_PENDING: 'INIT_PENDING',
  INIT_FAIL: 'INIT_FAIL',

  IDENTITY_GET_SUCCESS: 'IDENTITY_GET_SUCCESS',
  IDENTITY_LIST_SUCCESS: 'IDENTITY_LIST_SUCCESS',

  PROPOSAL_LIST_SUCCESS: 'PROPOSAL_LIST_SUCCESS',

  LOG_INFO: 'LOG_INFO',
  LOG_ERROR: 'LOG_ERROR',
  HEALTHCHECK_SUCCESS: 'HEALTHCHECK_SUCCESS',
  MYST_PROCESS_CLOSE: 'MYST_PROCESS_CLOSE',

  // ACTIONS
  IDENTITY_CREATE: 'IDENTITY_CREATE',
  IDENTITY_LIST: 'IDENTITY_LIST',

  PROPOSAL_LIST: 'PROPOSAL_LIST',

  SET_NAV: 'SET_NAV',
  SET_VISUAL: 'SET_VISUAL'
}
